Katsic-telegram-bot/ 
  - bot/
    - __init__.py
    - main.py
    - plugin_manager.py
  - plugins/ 
    - __init__.py
    - gtts_text_to_speech.py
    - auto_tts.py
    - ... (other plugin files)
  - .profile.d/
    - startup.sh
  - requirements.txt 
  - Procfile
